tasks:
  - name: Adding python testing dependencies
    before: echo 'Adding pip packages'
    init: pip install -r requirements.txt
    command: exit
    
  - name: Start web server
    init: python -m http.server 8000

  - name: Create run_test alias
    init: alias run_tests="/workspace/unittest-workshop/run_tests.sh"
    command: |
      chmod 777 /workspace/unittest-workshop/run_tests.sh
      clear

ports:
  - port: 8000
    onOpen: open-preview
