tasks:
  - name: Adding python testing dependencies
    before: echo 'Adding pip packages'
    init: pip install -r requirements.txt

  - name: Start web server
    init: python -m http.server 8000

  - name: Run tests alias
    init: alias run_tests="/workspace/unittest-workshop/run_tests.sh"

ports:
  - port: 8000
    onOpen: open-preview
